# Generated by Django 3.0.7 on 2023-04-13 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, unique=True)),
                ('horas_necessarias', models.IntegerField()),
                ('prazo_estimado', models.DateField()),
                ('horas_realizadas', models.IntegerField()),
                ('ultima_atualizacao', models.DateField()),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projetos', to='empresa.Departamento')),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('rg', models.CharField(max_length=10, unique=True)),
                ('sexo', models.CharField(max_length=1)),
                ('data_nascimento', models.DateField()),
                ('habilitacao', models.BooleanField(default=False)),
                ('salario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('carga_horaria_semanal', models.IntegerField()),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funcionarios', to='empresa.Departamento')),
            ],
        ),
    ]
