# Generated by Django 3.0.7 on 2023-04-14 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionario',
            name='departamento',
        ),
        migrations.AddField(
            model_name='departamento',
            name='lista_funcionarios',
            field=models.ManyToManyField(to='empresa.Funcionario', verbose_name='Lista de Funcionários'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='func_departamento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='funcionarios', to='empresa.Departamento'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='supervisor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='funcionarios', to='empresa.Funcionario'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='carga_horaria_semanal',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='sexo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], max_length=1),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='departamento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projetos', to='empresa.Departamento'),
        ),
    ]
