# Generated by Django 3.0.7 on 2023-04-14 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0002_auto_20230414_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='func_departamento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='funcionarios', to='empresa.Departamento', verbose_name='Departamento'),
        ),
        migrations.CreateModel(
            name='ParticipacaoProjeto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_trabalhadas', models.DecimalField(decimal_places=2, max_digits=6)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.Funcionario')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.Projeto')),
            ],
            options={
                'unique_together': {('funcionario', 'projeto')},
            },
        ),
    ]
