# Generated by Django 3.0.7 on 2023-04-15 02:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0003_auto_20230414_1456'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departamento',
            name='lista_funcionarios',
        ),
        migrations.AddField(
            model_name='projeto',
            name='funcionarios',
            field=models.ManyToManyField(related_name='projeto_funcionarios', to='empresa.Funcionario'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='supervisor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projeto_supervisor', to='empresa.Funcionario'),
        ),
        migrations.AlterUniqueTogether(
            name='projeto',
            unique_together={('nome', 'departamento')},
        ),
        migrations.DeleteModel(
            name='ParticipacaoProjeto',
        ),
    ]
